### ISSUE TITLE
Meta-arcade unnecessarily initializes pygame audio

### ISSUE THREAD

**Issue by schmidtdominik** [lifelong-learning-systems/meta-arcade#1]
I'm using meta-arcade in headless mode in a vectorized setup and each time meta-arcade is imported, it prints `ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection terminated` (probably because there is no audio output available).

This can be solved by replacing `pygame.init()` with `pygame.display.init()` since meta-arcade doesn't need audio output anyway.

**Comment by TedStaleyAPL** [comment]
Just pushed this change, thanks for the fix!
